name: Update Price Data

on:
  schedule:
    - cron: '00 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python Script
      run: python update_price.py
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        PRICE_API_KEY: ${{ secrets.PRICE_API_KEY }}

    - name: Commit and push changes
      run: |
        git config user.email "jyihaan4@naver.com"
        git config user.name "Jung Jaeyoung"
    
        git add ./output/price/*.csv
        git clean -xdf
        git commit -m "Update Data - $(TZ='Asia/Seoul' date +'%Y-%m-%d')"
        git push  
